# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Thu Jul 26 14:02:04 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 414)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 301, 341))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.loginEdit = QtGui.QLineEdit(self.groupBox)
        self.loginEdit.setGeometry(QtCore.QRect(90, 18, 113, 20))
        self.loginEdit.setObjectName(_fromUtf8("loginEdit"))
        self.passwordEdit = QtGui.QLineEdit(self.groupBox)
        self.passwordEdit.setGeometry(QtCore.QRect(90, 50, 113, 20))
        self.passwordEdit.setInputMask(_fromUtf8(""))
        self.passwordEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEdit.setObjectName(_fromUtf8("passwordEdit"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 51, 71, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.traiterButton = QtGui.QPushButton(self.groupBox)
        self.traiterButton.setGeometry(QtCore.QRect(90, 80, 75, 23))
        self.traiterButton.setObjectName(_fromUtf8("traiterButton"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(5, 130, 291, 192))
        self.tableWidget.setMaximumSize(QtCore.QSize(391, 16777215))
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.loginEdit2 = QtGui.QLineEdit(self.groupBox)
        self.loginEdit2.setGeometry(QtCore.QRect(210, 18, 71, 20))
        self.loginEdit2.setReadOnly(True)
        self.loginEdit2.setObjectName(_fromUtf8("loginEdit2"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(215, 52, 70, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.supprimerButton = QtGui.QPushButton(self.groupBox)
        self.supprimerButton.setGeometry(QtCore.QRect(170, 80, 75, 23))
        self.supprimerButton.setObjectName(_fromUtf8("supprimerButton"))
        self.initButton = QtGui.QPushButton(self.groupBox)
        self.initButton.setGeometry(QtCore.QRect(250, 80, 41, 23))
        self.initButton.setObjectName(_fromUtf8("initButton"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 10, 391, 361))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.traitementBox = QtGui.QComboBox(self.groupBox_2)
        self.traitementBox.setEnabled(False)
        self.traitementBox.setGeometry(QtCore.QRect(112, 20, 191, 22))
        self.traitementBox.setObjectName(_fromUtf8("traitementBox"))
        self.traitementBox.addItem(_fromUtf8(""))
        self.traitementBox.setItemText(0, _fromUtf8(""))
        self.traitementBox.addItem(_fromUtf8(""))
        self.traitementBox.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 23, 91, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.checkBoxActiverTraitement = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxActiverTraitement.setGeometry(QtCore.QRect(310, 22, 70, 17))
        self.checkBoxActiverTraitement.setObjectName(_fromUtf8("checkBoxActiverTraitement"))
        self.num_compte_en_coursEdit = QtGui.QLineEdit(self.groupBox_2)
        self.num_compte_en_coursEdit.setEnabled(False)
        self.num_compte_en_coursEdit.setGeometry(QtCore.QRect(137, 53, 41, 20))
        self.num_compte_en_coursEdit.setObjectName(_fromUtf8("num_compte_en_coursEdit"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 56, 121, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.checkBoxActivercompte_en_cours = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxActivercompte_en_cours.setGeometry(QtCore.QRect(185, 55, 70, 17))
        self.checkBoxActivercompte_en_cours.setObjectName(_fromUtf8("checkBoxActivercompte_en_cours"))
        self.nombreTraiteEdit = QtGui.QLineEdit(self.groupBox_2)
        self.nombreTraiteEdit.setEnabled(False)
        self.nombreTraiteEdit.setGeometry(QtCore.QRect(113, 84, 81, 20))
        self.nombreTraiteEdit.setObjectName(_fromUtf8("nombreTraiteEdit"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(11, 86, 71, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.plainTextAenvoyer = QtGui.QPlainTextEdit(self.groupBox_2)
        self.plainTextAenvoyer.setGeometry(QtCore.QRect(110, 120, 271, 151))
        self.plainTextAenvoyer.setTabChangesFocus(True)
        self.plainTextAenvoyer.setObjectName(_fromUtf8("plainTextAenvoyer"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 119, 81, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.mettreajourButton = QtGui.QPushButton(self.groupBox_2)
        self.mettreajourButton.setGeometry(QtCore.QRect(110, 334, 75, 23))
        self.mettreajourButton.setObjectName(_fromUtf8("mettreajourButton"))
        self.commencerButton = QtGui.QPushButton(self.groupBox_2)
        self.commencerButton.setGeometry(QtCore.QRect(190, 334, 75, 23))
        self.commencerButton.setObjectName(_fromUtf8("commencerButton"))
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(270, 334, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.rafraichirButton = QtGui.QPushButton(self.groupBox_2)
        self.rafraichirButton.setGeometry(QtCore.QRect(210, 83, 61, 23))
        self.rafraichirButton.setObjectName(_fromUtf8("rafraichirButton"))
        self.rechercheEdit = QtGui.QLineEdit(self.groupBox_2)
        self.rechercheEdit.setGeometry(QtCore.QRect(110, 290, 271, 20))
        self.rechercheEdit.setObjectName(_fromUtf8("rechercheEdit"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(11, 293, 61, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.compteCarEdit = QtGui.QLineEdit(self.groupBox_2)
        self.compteCarEdit.setGeometry(QtCore.QRect(330, 270, 51, 20))
        self.compteCarEdit.setObjectName(_fromUtf8("compteCarEdit"))
        self.checkBoxActiverPlain = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxActiverPlain.setGeometry(QtCore.QRect(257, 272, 70, 17))
        self.checkBoxActiverPlain.setObjectName(_fromUtf8("checkBoxActiverPlain"))
        self.nombreEnvoiEdit = QtGui.QLineEdit(self.groupBox_2)
        self.nombreEnvoiEdit.setGeometry(QtCore.QRect(146, 313, 50, 20))
        self.nombreEnvoiEdit.setObjectName(_fromUtf8("nombreEnvoiEdit"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(11, 316, 131, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.checkBoxNombreEnvoi = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxNombreEnvoi.setGeometry(QtCore.QRect(210, 316, 141, 17))
        self.checkBoxNombreEnvoi.setObjectName(_fromUtf8("checkBoxNombreEnvoi"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Envoi de message via linkedin", None))
        self.groupBox.setTitle(_translate("MainWindow", "Comptes", None))
        self.label.setText(_translate("MainWindow", "Login", None))
        self.label_2.setText(_translate("MainWindow", "Mot de passe", None))
        self.traiterButton.setText(_translate("MainWindow", "Ajouter", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Login", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mot de passe", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.checkBox.setText(_translate("MainWindow", "afficher", None))
        self.supprimerButton.setText(_translate("MainWindow", "Supprimer", None))
        self.initButton.setText(_translate("MainWindow", "init", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Parametres", None))
        self.traitementBox.setItemText(1, _translate("MainWindow", "commencer_page_1", None))
        self.traitementBox.setItemText(2, _translate("MainWindow", "continuer", None))
        self.label_3.setText(_translate("MainWindow", "Traitement", None))
        self.checkBoxActiverTraitement.setText(_translate("MainWindow", "activer", None))
        self.label_4.setText(_translate("MainWindow", "Numero compte en cours", None))
        self.checkBoxActivercompte_en_cours.setText(_translate("MainWindow", "activer", None))
        self.label_5.setText(_translate("MainWindow", "Nombre traité", None))
        self.label_6.setText(_translate("MainWindow", "Texte à envoyer", None))
        self.mettreajourButton.setText(_translate("MainWindow", "Mettre à jour", None))
        self.commencerButton.setText(_translate("MainWindow", "Commencer", None))
        self.pushButton.setText(_translate("MainWindow", "Arrêter", None))
        self.rafraichirButton.setText(_translate("MainWindow", "Rafraichir", None))
        self.label_7.setText(_translate("MainWindow", "Rechercher", None))
        self.checkBoxActiverPlain.setText(_translate("MainWindow", "activer", None))
        self.label_8.setText(_translate("MainWindow", "Nombre envoi par compte", None))
        self.checkBoxNombreEnvoi.setText(_translate("MainWindow", "appliquer nombre d\'envoi", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

